# Copy aminer CTI dashboard
- name: Copy CTI dashboard file
  copy:
    src: '{{ dashboard_path }}'
    dest: /home/

- name: Install plugin into Kibana
  shell: '/usr/share/kibana/bin/kibana-plugin install file:///home/{{dashboard_name}}'
